//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class feesstructure
    {
        public string Name { get; set; }
        public int Amount { get; set; }
        public int Applicability { get; set; }
        public int no { get; set; }
    }
}
