//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class guardiandetail
    {
        public string RegistrationNumber { get; set; }
        public string FathersName_MaleGuardian_ { get; set; }
        public string MothersName_FemaleGuardian_ { get; set; }
        public string ContactDetail { get; set; }
        public string AlternativeContact { get; set; }
        public string ContactEmail { get; set; }
        public int guardiansNo { get; set; }
    }
}
