//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int Adm_No { get; set; }
        public string StudentsName { get; set; }
        public string Surname { get; set; }
        public string RegistrationNumber { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string MedicalDetails { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string AcademicYear { get; set; }
        public string AcademicLevel { get; set; }
        public string Stream { get; set; }
    }
}
