//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactionhistory
    {
        public int RegistrationNumber { get; set; }
        public int AmountPaid { get; set; }
        public string PaymentFor { get; set; }
        public string PaymentMethod { get; set; }
        public string MethodDetails { get; set; }
        public System.DateTime DatePaid { get; set; }
        public System.DateTime Datestamp { get; set; }
        public int transactionNO { get; set; }
        public int Balance { get; set; }
    }
}
