//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_role
    {
        public user_role()
        {
            this.users = new HashSet<user>();
        }
    
        public int user_id { get; set; }
        public string Name { get; set; }
        public string desc { get; set; }
    
        public virtual ICollection<user> users { get; set; }
    }
}
